name: Self Report

on:
  schedule:
    - cron: "30 22,4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Report Without OpenVPN
        if: always()
        env:
          users: ${{ secrets.USERS }}
          send: ${{ secrets.SEND }}
        run: |
          if python -u main.py gh; then
            if [ -f "./use_ovpn" ]; then
              echo "use_ovpn=1" >> $GITHUB_ENV;
            fi
          else
            echo "use_ovpn=1" >> $GITHUB_ENV;
          fi

      - name: Configure OpenVPN
        if: always() && env.use_ovpn == 1
        env:
          users: ${{ secrets.USERS }}
        run: |
          sudo apt update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          python3 ovpn.py
          touch vpn.log

      - name: Connect and Test OpenVPN Connection
        if: always() && env.use_ovpn == 1
        run: sudo ./ovpn.sh

      - name: Report With OpenVPN
        if: always() && env.use_ovpn == 1
        env:
          users: ${{ secrets.USERS }}
          send: ${{ secrets.SEND }}
        run: "python -u main.py gh"

      - name: Kill OpenVPN Connection
        if: always() && env.use_ovpn == 1
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn

      - name: Upload VPN logs
        if: always() && env.use_ovpn == 1
        uses: actions/upload-artifact@v2
        with:
          name: VPN logs
          path: vpn.log